---
openapi: 3.0.1
info:
  title: VESPA API V1
  version: v1
paths:
  "/api/v1/motorcycles":
    get:
      summary: Retrieve all motorcycles
      tags:
      - Motorcycles
      responses:
        '200':
          description: OK
          content:
            application/json:
              examples:
                example_0:
                  value:
                  - id: 1
                    name: Motorcycle 1
                    model: Model 1
                    description: Description 1
                    photo: Photo 1
                    user_id: 1
                  - id: 2
                    name: Motorcycle 2
                    model: Model 2
                    description: Description 2
                    photo: Photo 2
                    user_id: 1
        '404':
          description: Resource not found
    post:
      summary: Create a motorcycle
      tags:
      - Motorcycles
      parameters: []
      responses:
        '201':
          description: Created
        '422':
          description: Unprocessable Entity
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                model:
                  type: string
                description:
                  type: string
                photo:
                  type: string
              required:
              - name
              - model
              - description
              - photo
  "/api/v1/motorcycles/{id}":
    parameters:
    - name: id
      in: path
      required: true
      schema:
        type: integer
    get:
      summary: Retrieve a specific motorcycle
      tags:
      - Motorcycles
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  model:
                    type: string
                  description:
                    type: string
                  photo:
                    type: string
                  user_id:
                    type: integer
                required:
                - id
                - name
                - model
                - description
                - photo
                - user_id
        '404':
          description: Resource not found
    delete:
      summary: Delete a motorcycle
      tags:
      - Motorcycles
      responses:
        '200':
          description: OK
        '404':
          description: Resource not found
  "/api/v1/reservations":
    get:
      summary: Retrieve all reservations
      tags:
      - Reservations
      responses:
        '200':
          description: OK
          content:
            application/json:
              examples:
                example_0:
                  value:
                  - id: 1
                    start_date: '2023-09-25'
                    end_date: '2023-09-28'
                    city: City 1
                    user_id: 1
                    motorcycle_id: 1
                  - id: 2
                    start_date: '2023-10-01'
                    end_date: '2023-10-05'
                    city: City 2
                    user_id: 1
                    motorcycle_id: 2
    post:
      summary: Create a reservation
      tags:
      - Reservations
      parameters: []
      responses:
        '201':
          description: Created
        '422':
          description: Unprocessable Entity
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                start_date:
                  type: string
                  format: date
                end_date:
                  type: string
                  format: date
                city:
                  type: string
                user_id:
                  type: integer
                motorcycle_id:
                  type: integer
              required:
              - start_date
              - end_date
              - city
              - user_id
              - motorcycle_id
  "/api/v1/reservations/{id}":
    parameters:
    - name: id
      in: path
      required: true
      schema:
        type: integer
    get:
      summary: Retrieve a specific reservation
      tags:
      - Reservations
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  start_date:
                    type: string
                    format: date
                  end_date:
                    type: string
                    format: date
                  city:
                    type: string
                  user_id:
                    type: integer
                  motorcycle_id:
                    type: integer
                required:
                - id
                - start_date
                - end_date
                - city
                - user_id
                - motorcycle_id
        '404':
          description: Resource not found
    delete:
      summary: Delete a reservation
      tags:
      - Reservations
      responses:
        '204':
          description: No Content
servers:
- url: https://vespa.onrender.com/
  variables:
    defaultHost:
      default: https://vespa.onrender.com/
